import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";
import theme from "@/theme";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import { MantineProvider } from "@mantine/core";
import { mantineTheme } from "@/mantineTheme";
import NavBar from "@/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Administrador - Aqua Maris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
        <ThemeProvider theme={theme}>
          <MantineProvider theme={mantineTheme}>
            <CssBaseline />

            <div className="pt-4 pb-4  bg-body lg:flex-row h-full lg:h-screen">
              <div className="h-full grid grid-cols-12 gap-4">
                <div className="col-span-3">
                  <div className="w-full h-full">
                    <NavBar />
                  </div>
                </div>
                <div className="col-span-9">{children}</div>
              </div>
            </div>
          </MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
